config/routes.rb
Rails.application.routes.draw do 
  resources :events do
    resources :comments
  end
  get 'feed' => 'events#feed'
  get 'resolved/index'

  get 'welcome/index'
  
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  accepts_nested_attributes_for :event
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, dependent: :destroy
  accepts_nested_attributes_for :comments
  validates :title, presence: true,
                    length: { minimum: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @event = Event.find(params[:event_id])
    @comment = @event.comments.new
  end
  def show
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
  end
  def create
    @event = Event.find(params[:event_id])
    @comment = @event.comments.create(comment_params)
    updatehash = { "resolved" => params[:comment][:event_attributes][:resolved]}
    @event.update(updatehash)
    redirect_to event_path(@event)
  end
 def destroy
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    @comment.destroy
    redirect_to event_path(@event)
  end
  def edit
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
  end
  def update
    @event = Event.find(params[:event_id])
    @comment = @event.comments.find(params[:id])
    updatehash = { "resolved" => params[:comment][:event_attributes][:resolved]}
    if @comment.update(comment_params)
      @event.update(updatehash)
      redirect_to event_path(@event)
    else
      render 'edit'
    end
  end
  private
    def comment_params
      params.require(:comment).permit(:commenter, :body)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.paginate(:page => params[:page], :per_page => 5)
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def new
    @event = Event.new
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def create       
    @event = Event.new(event_params)
    
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
    
  end
  def feed
    @events = Event.where("resolved = ?", false)
    respond_to do |format|
      format.html
      format.rss { render :layout => false }
    end
  end
  def update
    @event = Event.find(params[:id])
    
    if @event.update(event_params)
      redirect_to @event
    else
      render 'edit'
    end
    
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
 
    redirect_to events_path
  end
  
  private 
    def event_params
      if !params[:event][:year].blank?
      datetime = DateTime.new(params[:event][:year].to_i, params[:event][:month].to_i, params[:event][:day].to_i, params[:event][:hour].to_i, params[:event][:minute].to_i)
      datetimehash = { "datetime" => datetime}
      end
      if params[:event][:resolved]
        resolvetime = Time.now + 3600
        resolvetimehash = { "resolvetime" => resolvetime}
      end
      others = params.require(:event).permit(:title, :text, :status,:resolved) 
      if params[:event][:resolved]
        mergehashone = others.merge(datetimehash)
        mergehashtwo = mergehashone.merge(resolvetimehash)
        return mergehashtwo
      else
        mergehashone = others.merge(datetimehash)
        return mergehashone
      end

      
    end
    
end

app/controllers/resolved_controller.rb
class ResolvedController < ApplicationController
  def index
    time = Time.now + 3600
    resolved = Event.where("resolved = ? and datetime <= ?", true, time)
    @resolvedpageinate = resolved.paginate(:page => params[:page], :per_page => 5)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    time = Time.now + 3600
    @active = Event.where("resolved = ? and datetime <= ?", false, time)
    future = Event.where(["resolved = ? and datetime > ?", false, time])
    @futurepage = future.paginate(:page => params[:page], :per_page => 5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/resolved_helper.rb
module ResolvedHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/edit.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
 		</ul>
	</div>
</div>
<div id ="content">
	<div class="inner">
		<div class="options">
		<h4 class ="back"><%= link_to 'Back', event_path(@event) %></h4>
		</div>
		<h1>Add a Comment:</h1>
			<br>
			<%= form_with(model: [ @event, @event.comments.find(params[:id]) ]) do |form| %>
			  <p>
			    <%= form.label :commenter %><br>
			    <%= form.text_field :commenter %>
			  </p>
			  <br>
			  <p>
			    <%= form.label :body %><br>
			    <%= form.text_area :body %>
			  </p>
			  <br>
		  	<%= form.fields_for :event, url: events_path, local: true do |e| %>
    		<%= e.label :resolved %>
		  	<%= e.select :resolved, [['Active','false'],['Resolved','true']]%>
			<% end %>
		  	<br>
		  	<br />
			  <p>
			    <%= form.submit %>
			  </p>
			<% end %>
	</div>
</div>

app/views/comments/new.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
 		</ul>
	</div>
</div>
<div id ="content">
	<div class="inner">
		<div class="options">
		<h4 class ="back"><%= link_to 'Back', event_path(@event) %></h4>
		</div>
		<h1>Add a Comment:</h1>
			<br>
			<%= form_with(model: [ @event, @event.comments.build ], local: true) do |form| %>
			  <p>
			    <%= form.label :commenter %><br>
			    <%= form.text_field :commenter %>
			  </p>
			  <br>
			  <p>
			    <%= form.label :body %><br>
			    <%= form.text_area :body %>
			  </p>
			  <br>
		  	<%= form.fields_for :event, url: events_path, local: true do |e| %>
    		<%= e.label :resolved %>
		  	<%= e.select :resolved, [['Active','false'],['Resolved','true']]%>
			<% end %>
		  	<br>
		  	<br />
			  <p>
			    <%= form.submit %>
			  </p>
			<% end %>
	</div>
</div>

app/views/comments/show.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
 		</ul>
	</div>
</div>
<div id ="content">
	<div class="inner">
		<div class = "options">
			<h4 class="showedit"><%= link_to 'Edit', edit_event_comment_path(@event,@comment) %></h4>
			<h4 class="back"><%= link_to 'Back', event_path(@event) %></h4>
		</div>
		<h1>Commenter: <%=@comment.commenter%></h1>
		<div class="afm cfm">
				<p>Comment Body:</p>	 
			  <p>
			    <%= @comment.body %>
			  </p>
			  </div>
	</div>
</div>

app/views/events/edit.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Scheduled Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
 		</ul>
 	</div>
</div>
<div id ="content">
	<div class="inner">
		<div class="options">
		<h4 class ="back"><%= link_to 'Back', events_path %></h4>
		</div>
		<h1>Edit Event</h1>
		 
		<%= form_with(model: @event) do |form| %>
		 <% if @event.errors.any? %>
		    <div id="error_explanation">
		      <h2>
		        <%= pluralize(@event.errors.count, "error") %> prohibited
		        this event from being saved:
		      </h2>
		      <ul>
		        <% @event.errors.full_messages.each do |msg| %>
		          <li><%= msg %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <br>
		  <p>
		    <%= form.label :title %><br>
		    <%= form.text_field :title %>
		  </p>
		 <br>
		  <p>
		    <%= form.label :text %><br>
		    <%= form.text_area :text %>
		  </p>
		  <br>
		 <p>
		  	<%= form.label :status %>
		  	<%= form.select :status, [['Critical','critical'],['Severe','severe'],['Important','important']]%>
		  </p>
		  <br>
		  <p>
		  	<%= form.label(:datetime, "Date and Time")%>
		    <%= select_datetime @event.datetime, prefix: :event %>
		  </p>
		  <br>
		  <p>
		  	<%= form.label :resolved %>
		  	<%= form.select :resolved, [['Active','false'],['Resolved','true']]%>
		  </p>
		  <br>
		  <p>
		    <%= form.submit %>
		  </p>
		 
		<% end %>
		 
	</div>
</div>

app/views/events/index.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
 		</ul>
 	</div>
</div>
<div id ="content">
	<div class = "inner">
		<h3 class= "future" >All Events</h3>
		<ul  class = "events resolved">
			<%if !@events.blank? %>
		  	<% @events.each do |event| %>
		      	<li class = "event" style>
		      	<div class = "stat">			      
			      	<% if event.resolved %>
			      		<h4 class ="resolved">Resolved</h4>
			      	<%else%>
			      		<h4 class ="active">Active</h4>
			      	<% end%>
			      	<% case event.status%>
			      	<%when "critical"%>
			      		<h4 class= "critical">Critical</h4>
			      	<%when "severe"%>
			      		<h4 class= "severe">Severe</h4>
			      	<%when "important"%>
			      		<h4 class= "important">Important</h4>
			      	<%end%>
		      	</div>
		      	
		      	<h4 class ="title"><%= link_to event.title, event_path(event) %></h4>
		      	<p class = "date"><%= event.datetime%></p>
		      	
		      	<div class = "options">
		      		
		      		<h4 class="edit"><%= link_to 'Edit', edit_event_path(event)%></h4>
		      		<h4 class="destroy"><%= link_to 'Destroy', event_path(event),method: :delete, data: { confirm: 'Are you sure?' } %></h4>
		      		
		      	</div>

		      </li>
		    
		  	<% end %>
		  	<%else%>
		  		<h2>There are currently no Resolved, Active or Scheduled events</h2>
		  	<%end%>
		  </ul>
				<%= will_paginate @events %>
	</div>
</div>

app/views/events/new.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>			
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
 		</ul>
 	</div>
</div>
<div id="content">
	<div class="inner">
		<div class="options">
		<h4 class ="back"><%= link_to 'Back', events_path %></h4>
		</div>
		<h1>Create New Event</h1>
		
		
		<%= form_with scope: :event, url: events_path, local: true do |form| %>
			<% if @event.errors.any? %>
		    <div id="error_explanation">
		      <h2>
		        <%= pluralize(@event.errors.count, "error") %> prohibited
		        this event from being saved:
		      </h2>
		      <ul>
		        <% @event.errors.full_messages.each do |msg| %>
		          <li><%= msg %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>
		  <br>
		  <p>
		    <%= form.label :title %><br>
		    <%= form.text_field :title %>
		  </p>
		 <br>
		  <p>
		    <%= form.label :text %><br>
		    <%= form.text_area :text %>
		  </p>
		  <br>
		  <p>
		  	<%= form.label :status %>
		  	<%= form.select :status, [['Critical','critical'],['Severe','severe'],['Important','important']]%>
		  </p>
		  <br>
		  <p>
		  	<%= form.label(:datetime, "Date and Time")%>
		    <%= select_datetime Time.now, prefix: :event %>
		  </p>
		  <br>
		  <p>
		  	<%= form.label :resolved %>
		  	<%= form.select :resolved, [['Active','false'],['Resolved','true']]%>
		  </p>
		  <br>
		  <p>
		    <%= form.submit %> 
		  </p>
		<% end %>
	</div>
</div>

app/views/events/show.html.erb
<div id ="header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
 			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
 			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
 		</ul>
	</div>
</div>
<div id ="content">
	<div class="inner">
		<div class = "stat">			      
			      	<% if @event.resolved %>
			      		<h4 class ="resolved">Resolved</h4>
			      	<%else%>
			      		<h4 class ="active">Active</h4>
			      	<% end%>
			      	<% case @event.status%>
			      	<%when "critical"%>
			      		<h4 class= "critical">Critical</h4>
			      	<%when "severe"%>
			      		<h4 class= "severe">Severe</h4>
			      	<%when "important"%>
			      		<h4 class= "important">Important</h4>
			      	<%end%>
		      	</div>
		<h1><%= @event.title %></h1>
		<%if @event.resolved%>
			<p class="meta">Resolved at: <%= @event.resolvetime %></p>
		<%else%>
			<p class="meta">Last updated at: <%= @event.updated_at+3600%></p>
		<%end%>
		<div class="afm cfm">
			<p><%= @event.text%></p>
		</div>
		<div class = "options">
			<h4 class="showedit"><%= link_to 'Edit', edit_event_path(@event) %></h4>
			<h4 class="back"><%= link_to 'Back', events_path %></h4>
		</div>
		<div id="comments">
			<h2>Latest update</h2>
			<div class="comment">
			<% @event.comments.each do |comment| %>
				<h4 class="meta">Updated at:<%=comment.updated_at+3600%> by <%= comment.commenter %></h4>	
				<div class = "options">
				<h4 class="showedit"><%= link_to 'Edit', edit_event_comment_path(@event,comment) %></h4>
  				<h4 class="delete"><%= link_to 'Delete Comment', [comment.event, comment], method: :delete,data: { confirm: 'Are you sure?' } %></h4>
				</div>
				<div class="afm cfm">	 
			  <p>
			    <%= comment.body %>
			  </p>
			  </div>
			<% end %>
			</div>
			<h2 class="addcomment"><%= link_to 'Add Comment:', new_event_comment_path(@event) %></h2>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StatusCheck</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "reset.css" %>
    <%= stylesheet_link_tag "afm.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resolved/index.html.erb
<div id = "header">
	<div class = "inner">
		<h1>Status Checker</h1>
		<ul>
			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
		</ul>
	</div>
</div>
<div id = "content">
	<div class = "inner">
		<h3 class= "future" >Resolved Events</h3>
		<ul  class = "events resolved">
			<%if !@resolvedpageinate.blank? %>
		  	<% @resolvedpageinate.each do |event| %>
		      	<li class = "event" style>
		      	<div class = "stat">			      
			      	<% if event.resolved %>
			      		<h4 class ="resolved">Resolved</h4>
			      	<%else%>
			      		<h4 class ="active">Active</h4>
			      	<% end%>
			      	<% case event.status%>
			      	<%when "critical"%>
			      		<h4 class= "critical">Critical</h4>
			      	<%when "severe"%>
			      		<h4 class= "severe">Severe</h4>
			      	<%when "important"%>
			      		<h4 class= "important">Important</h4>
			      	<%end%>
		      	</div>
		      	
		      	<h4 class ="title"><%= link_to event.title, event_path(event) %></h4>
		      	<p class = "date">Resolved At:  <%= event.resolvetime%></p>		  
		      	<div class = "options">
		      		
		      		<h4 class="edit"><%= link_to 'Edit', edit_event_path(event)%></h4>
		      		<h4 class="destroy"><%= link_to 'Destroy', event_path(event),method: :delete, data: { confirm: 'Are you sure?' } %></h4>
		      		
		      	</div>    
		      </li>
		    
		  	<% end %>
		  	<%else%>
		  	<h2>There are currently no Resolved events</h2>
		  	<%end%>
		  	
		  </ul>
				<%= will_paginate @resolvedpageinate %>
	</div>
</div>

app/views/welcome/index.html.erb
<div id = header>
	<div class=inner>
		<h1>Status Checker</h1>
		<ul>
			<li><%= link_to 'Home Page', controller: 'welcome' %></li>
			<li><%= link_to 'List of All Scheduled Events', controller: 'events' %></li>
			<li><%= link_to 'List of All  Resolved Events', controller: 'resolved' %></li>
			<li><%= link_to 'RSS Feed', feed_path+".rss", :action => 'show', :format => :rss%></li>
			<li><%= link_to 'Create New Event', new_event_path %></li>
		</ul>
	</div>
</div>
<div id = "content">
	<div class = "inner">
		<h3 class= "future" >Active Events</h3>
		<ul  class = "events resolved">
			<%if !@active.blank? %>
		  	<% @active.each do |event| %>
		      	<li class = "event" style>
		      	<div class = "stat">			      
			      	<% if event.resolved %>
			      		<h4 class ="resolved">Resolved</h4>
			      	<%else%>
			      		<h4 class ="active">Active</h4>
			      	<% end%>
			      	<% case event.status%>
			      	<%when "critical"%>
			      		<h4 class= "critical">Critical</h4>
			      	<%when "severe"%>
			      		<h4 class= "severe">Severe</h4>
			      	<%when "important"%>
			      		<h4 class= "important">Important</h4>
			      	<%end%>
		      	</div>
		      	
		      	<h4 class ="title"><%= link_to event.title, event_path(event) %></h4>
		      	<p class = "date">Last Updated:  <%= event.datetime%></p>
		      	<div class = "options">
		      		
		      		<h4 class="edit"><%= link_to 'Edit', edit_event_path(event)%></h4>
		      		<h4 class="destroy"><%= link_to 'Destroy', event_path(event),method: :delete, data: { confirm: 'Are you sure?' } %></h4>
		      		
		      	</div>		      
		      </li>
		    
		  	<% end %>
		  	<%else%>
		  		<h2>There are currently no active events</h2>
		  	<%end%>
		  </ul>
		<h3 class= "future" >Future Events</h3>
		<ul  class = "events resolved">
			<%if !@futurepage.blank? %>
		  	<% @futurepage.each do |event| %>
		      	<li class = "event" style>
		      	<div class = "stat">			      
			      	<% if event.resolved %>
			      		<h4 class ="resolved">Resolved</h4>
			      	<%else%>
			      		<h4 class ="active">Active</h4>
			      	<% end%>
			      	<% case event.status%>
			      	<%when "critical"%>
			      		<h4 class= "critical">Critical</h4>
			      	<%when "severe"%>
			      		<h4 class= "severe">Severe</h4>
			      	<%when "important"%>
			      		<h4 class= "important">Important</h4>
			      	<%end%>
		      	</div>
		      	
		      	<h4 class ="title"><%= link_to event.title, event_path(event) %></h4>
		      	<p class = "date">Scheduled For:  <%= event.datetime%></p>		
		      	<div class = "options">
		      		
		      		<h4 class="edit"><%= link_to 'Edit', edit_event_path(event)%></h4>
		      		<h4 class="destroy"><%= link_to 'Destroy', event_path(event),method: :delete, data: { confirm: 'Are you sure?' } %></h4>
		      		
		      	</div>      
		      </li>
		    
		  	<% end %>
		  	<%else%>
		  		<h2>There are currently no Scheduled events</h2>
		  	<%end%>		  	
		  </ul>
				<%= will_paginate @futurepage %>
	</div class = inner>
</div>